<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Exceptions on </title>
    <link>http://localhost:1313/fr/tags/exceptions/</link>
    <description>Recent content in Exceptions on </description>
    <generator>Hugo -- gohugo.io</generator>
    <language>fr</language>
    <managingEditor>achafine@gmail.com (Châ-Fine Ayédoun ADEBI)</managingEditor>
    <webMaster>achafine@gmail.com (Châ-Fine Ayédoun ADEBI)</webMaster>
    <copyright>&amp;copy; 2025 Ayédoun Châ-Fine ADEBI. All Rights Reserved.</copyright>
    <lastBuildDate>Tue, 04 Mar 2025 02:08:27 +0100</lastBuildDate><atom:link href="http://localhost:1313/fr/tags/exceptions/index.xml" rel="self" type="application/rss+xml" />
    
    <item>
      <title>Les exceptions en Python</title>
      <link>http://localhost:1313/fr/courses/python/try-except/</link>
      <pubDate>Tue, 04 Mar 2025 02:08:27 +0100</pubDate>
      <author>achafine@gmail.com (Châ-Fine Ayédoun ADEBI)</author>
      <guid>http://localhost:1313/fr/courses/python/try-except/</guid>
      <description></description>
      
    </item>
    
  </channel>
</rss>
